import { mockCustomers } from './mockData';
import { getIntegrationSettings } from './integrationConfig';
import { sendEmail, sendWhatsApp } from './communicationService';
import { upsertEventTask, notifyAssigneeOfTask, type Task } from './taskService';

export type ErpEventType =
  | 'enquiry.created'
  | 'order.ready_for_dispatch'
  | 'workorder.completed'
  | 'workorder.stage_changed'
  | 'order.status_update'
  | 'manual.message';

export type ErpEventPayload = {
  enquiryId?: string;
  orderId?: string;
  workOrderId?: string;
  customerId?: string;
  customerName?: string;
  customerEmail?: string;
  customerPhone?: string;
  contactPerson?: string;
  stage?: string;
  requirements?: string;
  expectedValue?: number;
  totalAmount?: number;
  status?: string;
};

function findCustomer(payload: ErpEventPayload) {
  if (payload.customerId) {
    return mockCustomers.find(c => c.id === payload.customerId);
  }
  return undefined;
}

async function createAndNotifyTask(task: Task): Promise<Task> {
  const saved = upsertEventTask(task);
  await notifyAssigneeOfTask(saved);
  return saved;
}

export async function processErpEvent(
  type: ErpEventType,
  payload: ErpEventPayload
): Promise<{ tasksCreated: string[]; notificationsSent: number }> {
  const settings = getIntegrationSettings();
  const tasksCreated: string[] = [];
  let notificationsSent = 0;
  const customer = findCustomer(payload);

  const customerName = payload.customerName || customer?.name || 'Customer';
  const customerEmail = payload.customerEmail || customer?.email;
  const customerPhone = payload.customerPhone || customer?.phone;
  const contactPerson = payload.contactPerson || customer?.contactPerson || customerName;

  if (type === 'enquiry.created' && payload.enquiryId) {
    if (settings.autoTasks.enabled) {
      const task = await createAndNotifyTask({
        id: `AUTO-ENQ-${payload.enquiryId}`,
        title: `Follow up on new Enquiry ${payload.enquiryId} — ${customerName} (₹${(payload.expectedValue || 0).toLocaleString('en-IN')})`,
        assignee: 'Sales Dept',
        due: 'Tomorrow',
        status: 'Pending',
        priority: 'High',
        isAutoGenerated: true,
        sourceType: 'enquiry',
        sourceId: payload.enquiryId,
        sourcePath: `/enquiries/${payload.enquiryId}`,
      });
      tasksCreated.push(task.id);
    }

    if (settings.whatsapp.enabled && settings.whatsapp.notifyOnEnquiry) {
      await sendWhatsApp({
        recipient: `${contactPerson} (${customerName})`,
        phone: customerPhone,
        type: 'Enquiry Acknowledgement',
        message: `Dear ${contactPerson},\n\nThank you for your enquiry ${payload.enquiryId}. Our sales team will contact you shortly.\n\nRequirements noted: ${payload.requirements || 'As discussed'}\n\n— Sumesh Petroleum`,
        sourceRef: payload.enquiryId,
      });
      notificationsSent++;
    }

    if (settings.email.enabled && settings.email.notifyOnEnquiry && customerEmail) {
      await sendEmail({
        to: customerEmail,
        type: 'Enquiry Acknowledgement',
        subject: `Enquiry ${payload.enquiryId} Received — Sumesh Petroleum`,
        body: `Dear ${contactPerson},\n\nWe have received your enquiry ${payload.enquiryId}.\n\nRequirements: ${payload.requirements || '—'}\nExpected Value: ₹${(payload.expectedValue || 0).toLocaleString('en-IN')}\n\nOur team will follow up within 24 hours.\n\nBest regards,\nSumesh Petroleum ERP`,
        sourceRef: payload.enquiryId,
      });
      notificationsSent++;

      await sendEmail({
        to: settings.email.ccInternal,
        type: 'Internal Sales Alert',
        subject: `New Enquiry ${payload.enquiryId} — ${customerName}`,
        body: `A new enquiry has been logged.\n\nCustomer: ${customerName}\nValue: ₹${(payload.expectedValue || 0).toLocaleString('en-IN')}\nRequirements: ${payload.requirements || '—'}`,
        sourceRef: payload.enquiryId,
      });
      notificationsSent++;
    }
  }

  if ((type === 'order.ready_for_dispatch' || type === 'workorder.completed') && payload.orderId) {
    if (settings.autoTasks.enabled) {
      const packTask = await createAndNotifyTask({
        id: `AUTO-PACK-${payload.orderId}`,
        title: `Configure Packing List for Order ${payload.orderId} — ${customerName}`,
        assignee: 'Logistics Desk',
        due: 'Today',
        status: 'Pending',
        priority: 'High',
        isAutoGenerated: true,
        sourceType: 'order',
        sourceId: payload.orderId,
        sourcePath: `/orders/${payload.orderId}`,
      });
      tasksCreated.push(packTask.id);

      const shipTask = await createAndNotifyTask({
        id: `AUTO-SHIP-${payload.orderId}`,
        title: `Prepare E-Way Bill & carrier for Order ${payload.orderId}`,
        assignee: 'Transport Desk',
        due: 'Today',
        status: 'Pending',
        priority: 'Medium',
        isAutoGenerated: true,
        sourceType: 'order',
        sourceId: payload.orderId,
        sourcePath: `/orders/${payload.orderId}`,
      });
      tasksCreated.push(shipTask.id);
    }

    if (settings.whatsapp.enabled && settings.whatsapp.notifyOnDispatch) {
      await sendWhatsApp({
        recipient: 'Transport Desk & Admin',
        phone: settings.whatsapp.businessPhone,
        type: 'Dispatch Readiness',
        message: `Order ${payload.orderId} for ${customerName} is Ready for Dispatch. Please configure packing list and assign carrier.`,
        sourceRef: payload.orderId,
      });
      if (customerPhone) {
        await sendWhatsApp({
          recipient: `${contactPerson} (${customerName})`,
          phone: customerPhone,
          type: 'Order Status',
          message: `Dear ${contactPerson},\n\nYour order *${payload.orderId}* is now *Ready for Dispatch*. We will share dispatch details shortly.\n\n— Sumesh Petroleum`,
          sourceRef: payload.orderId,
        });
      }
      notificationsSent += customerPhone ? 2 : 1;
    }

    if (settings.email.enabled && settings.email.notifyOnDispatch) {
      await sendEmail({
        to: settings.email.ccInternal,
        type: 'Dispatch Notification',
        subject: `Order ${payload.orderId} Ready for Dispatch`,
        body: `Order ${payload.orderId} (${customerName}) has been marked Ready for Dispatch.\n\nAction required: Packing list, E-Way bill, and carrier assignment.`,
        attachment: `${payload.orderId}_Ready.pdf`,
        sourceRef: payload.orderId,
      });
      notificationsSent++;

      if (customerEmail) {
        await sendEmail({
          to: customerEmail,
          type: 'Order Status Update',
          subject: `Order ${payload.orderId} — Ready for Dispatch`,
          body: `Dear ${contactPerson},\n\nYour order ${payload.orderId} is ready for dispatch. Our logistics team will coordinate shipment shortly.\n\nBest regards,\nSumesh Petroleum`,
          sourceRef: payload.orderId,
        });
        notificationsSent++;
      }
    }
  }

  if (type === 'workorder.stage_changed' && payload.workOrderId && payload.stage) {
    if (['Assembly', 'Testing'].includes(payload.stage) && settings.autoTasks.enabled) {
      const task = await createAndNotifyTask({
        id: `AUTO-WO-${payload.workOrderId}`,
        title: `Supervise ${payload.stage} for Job Card ${payload.workOrderId}`,
        assignee: 'Production Floor',
        due: 'Next Week',
        status: 'Pending',
        priority: 'Medium',
        isAutoGenerated: true,
        sourceType: 'work_order',
        sourceId: payload.workOrderId,
        sourcePath: `/work-orders/${payload.workOrderId}`,
      });
      tasksCreated.push(task.id);
    }

    if (settings.whatsapp.enabled && settings.whatsapp.notifyOnWorkOrder) {
      await sendWhatsApp({
        recipient: 'Production Supervisor',
        phone: settings.whatsapp.businessPhone,
        type: 'Production Update',
        message: `Job Card ${payload.workOrderId} entered *${payload.stage}* stage. Supervision required.`,
        sourceRef: payload.workOrderId,
      });
      notificationsSent++;
    }
  }

  if (type === 'order.status_update' && payload.orderId) {
    if (settings.email.enabled && customerEmail) {
      await sendEmail({
        to: customerEmail,
        type: 'Order Status Update',
        subject: `Order ${payload.orderId} Status: ${payload.status}`,
        body: `Dear ${contactPerson},\n\nYour order ${payload.orderId} status has been updated to: ${payload.status}.\nAmount: ₹${(payload.totalAmount || 0).toLocaleString('en-IN')}\n\n— Sumesh Petroleum ERP`,
        sourceRef: payload.orderId,
      });
      notificationsSent++;
    }
  }

  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('erp-event', { detail: { type, payload, tasksCreated, notificationsSent } }));
  }

  return { tasksCreated, notificationsSent };
}

/** @deprecated Use processErpEvent instead */
export async function triggerDispatchAlerts(orderId: string): Promise<void> {
  await processErpEvent('order.ready_for_dispatch', { orderId });
}
