import {
  getStoredEnquiries,
  getMockOrders,
  mockCustomers,
  mockProducts,
  mockPackingLists,
} from './mockData';
import { mockWorkOrders, type WorkOrder } from './mockData2';
import { getIntegrationSettings } from './integrationConfig';
import { sendEmail, sendWhatsApp } from './communicationService';

export type Task = {
  id: string;
  title: string;
  assignee: string;
  due: string;
  status: 'Pending' | 'Completed';
  priority: 'High' | 'Medium' | 'Low';
  isAutoGenerated?: boolean;
  sourceType?: string;
  sourceId?: string;
  sourcePath?: string;
  createdAt?: string;
};

const MANUAL_KEY = 'manualTasks';
const COMPLETED_KEY = 'completedTaskIds';
const EVENT_TASKS_KEY = 'sp2_event_tasks';

function loadWorkOrders(): WorkOrder[] {
  if (typeof window !== 'undefined') {
    const saved = localStorage.getItem('mockWorkOrders');
    if (saved) return JSON.parse(saved);
  }
  return mockWorkOrders;
}

export function getManualTasks(): Task[] {
  if (typeof window === 'undefined') return [];
  try {
    const saved = localStorage.getItem(MANUAL_KEY);
    if (saved) return JSON.parse(saved);
    return [{ id: 'TSK-103', title: 'Schedule AMC Visit for Reliance', assignee: 'Service Coordinator', due: '05-Jul-2026', status: 'Pending', priority: 'Low' }];
  } catch {
    return [];
  }
}

export function saveManualTasks(tasks: Task[]): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem(MANUAL_KEY, JSON.stringify(tasks));
}

export function getCompletedTaskIds(): string[] {
  if (typeof window === 'undefined') return [];
  try {
    const saved = localStorage.getItem(COMPLETED_KEY);
    return saved ? JSON.parse(saved) : ['TSK-100'];
  } catch {
    return [];
  }
}

export function saveCompletedTaskIds(ids: string[]): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem(COMPLETED_KEY, JSON.stringify(ids));
}

function getEventTasks(): Task[] {
  if (typeof window === 'undefined') return [];
  try {
    const saved = localStorage.getItem(EVENT_TASKS_KEY);
    return saved ? JSON.parse(saved) : [];
  } catch {
    return [];
  }
}

function saveEventTasks(tasks: Task[]): void {
  if (typeof window === 'undefined') return;
  localStorage.setItem(EVENT_TASKS_KEY, JSON.stringify(tasks));
}

export function upsertEventTask(task: Task): Task {
  const existing = getEventTasks();
  const idx = existing.findIndex(t => t.id === task.id);
  const withMeta = { ...task, isAutoGenerated: true, createdAt: task.createdAt || new Date().toISOString() };
  if (idx >= 0) {
    existing[idx] = withMeta;
  } else {
    existing.unshift(withMeta);
  }
  saveEventTasks(existing);
  notifyTasksUpdate();
  return withMeta;
}

/** Scan live ERP data and produce tasks from entity details */
export function generateAutoTasksFromDetails(): Task[] {
  const settings = getIntegrationSettings();
  if (!settings.autoTasks.enabled) return [];

  const autoTasks: Task[] = [];
  const enquiries = getStoredEnquiries();
  const orders = getMockOrders();
  const workOrders = loadWorkOrders();

  enquiries.forEach(enq => {
    if (enq.status === 'Open') {
      const cust = mockCustomers.find(c => c.id === enq.customerId);
      autoTasks.push({
        id: `AUTO-ENQ-${enq.id}`,
        title: `Follow up on Enquiry ${enq.id} — ${cust?.name || 'Customer'} (₹${enq.expectedValue.toLocaleString('en-IN')})`,
        assignee: 'Sales Dept',
        due: 'Tomorrow',
        status: 'Pending',
        priority: 'High',
        isAutoGenerated: true,
        sourceType: 'enquiry',
        sourceId: enq.id,
        sourcePath: `/enquiries/${enq.id}`,
      });
    }
  });

  orders.forEach(order => {
    const cust = mockCustomers.find(c => c.id === order.customerId);
    if (order.status === 'Ready for Dispatch') {
      const pl = mockPackingLists.find(p => p.orderId === order.id);
      if (!pl) {
        autoTasks.push({
          id: `AUTO-PACK-${order.id}`,
          title: `Finalize Packing List for Order ${order.id} — ${cust?.name || 'Customer'}`,
          assignee: 'Logistics Desk',
          due: 'Today',
          status: 'Pending',
          priority: 'High',
          isAutoGenerated: true,
          sourceType: 'order',
          sourceId: order.id,
          sourcePath: `/orders/${order.id}`,
        });
      } else if (pl.status === 'Finalized') {
        autoTasks.push({
          id: `AUTO-SHIP-${order.id}`,
          title: `Generate E-Way Bill & assign carrier for ${order.id} — ${cust?.name || 'Customer'}`,
          assignee: 'Transport Desk',
          due: 'Today',
          status: 'Pending',
          priority: 'Medium',
          isAutoGenerated: true,
          sourceType: 'order',
          sourceId: order.id,
          sourcePath: `/orders/${order.id}`,
        });
      }
    }
    if (order.status === 'In Production') {
      autoTasks.push({
        id: `AUTO-PROD-${order.id}`,
        title: `Monitor production progress for Order ${order.id} — ${cust?.name || 'Customer'}`,
        assignee: 'Production Floor',
        due: 'Next Week',
        status: 'Pending',
        priority: 'Medium',
        isAutoGenerated: true,
        sourceType: 'order',
        sourceId: order.id,
        sourcePath: `/orders/${order.id}`,
      });
    }
  });

  workOrders.forEach(wo => {
    if (wo.status === 'Assembly' || wo.status === 'Testing') {
      const prod = mockProducts.find(p => p.id === wo.productId);
      autoTasks.push({
        id: `AUTO-WO-${wo.id}`,
        title: `Supervise ${wo.status} for Job Card ${wo.id} — ${prod?.name || 'Product'}`,
        assignee: 'Production Floor',
        due: 'Next Week',
        status: 'Pending',
        priority: 'Medium',
        isAutoGenerated: true,
        sourceType: 'work_order',
        sourceId: wo.id,
        sourcePath: `/work-orders/${wo.id}`,
      });
    }
  });

  return autoTasks;
}

export function getAllActiveTasks(): Task[] {
  const completed = getCompletedTaskIds();
  const manual = getManualTasks().filter(t => !completed.includes(t.id));
  const eventTasks = getEventTasks().filter(t => !completed.includes(t.id));
  const scanned = generateAutoTasksFromDetails().filter(t => !completed.includes(t.id));

  const byId = new Map<string, Task>();
  [...scanned, ...eventTasks, ...manual].forEach(t => byId.set(t.id, t));
  return Array.from(byId.values());
}

export function getAllCompletedTasks(): Task[] {
  const completed = getCompletedTaskIds();
  const legacy: Task[] = [
    { id: 'TSK-100', title: 'Call back vendor regarding MS Plate quote.', assignee: 'Purchase Desk', due: 'Yesterday', status: 'Completed', priority: 'Medium' },
  ];
  const manual = getManualTasks().filter(t => completed.includes(t.id)).map(t => ({ ...t, status: 'Completed' as const }));
  const event = getEventTasks().filter(t => completed.includes(t.id)).map(t => ({ ...t, status: 'Completed' as const }));
  const scanned = generateAutoTasksFromDetails().filter(t => completed.includes(t.id)).map(t => ({ ...t, status: 'Completed' as const }));
  return [...legacy, ...manual, ...event, ...scanned];
}

export function markTaskDone(taskId: string): void {
  const ids = getCompletedTaskIds();
  if (!ids.includes(taskId)) {
    saveCompletedTaskIds([...ids, taskId]);
    notifyTasksUpdate();
  }
}

export function createManualTask(input: Omit<Task, 'id' | 'status' | 'isAutoGenerated'>): Task {
  const tasks = getManualTasks();
  const newTask: Task = {
    ...input,
    id: `TSK-${104 + tasks.length + getCompletedTaskIds().length}`,
    status: 'Pending',
  };
  saveManualTasks([...tasks, newTask]);
  notifyTasksUpdate();
  return newTask;
}

export async function notifyAssigneeOfTask(task: Task): Promise<void> {
  const settings = getIntegrationSettings();
  if (!task.isAutoGenerated) return;

  const message = `*ERP Task Assigned*\n${task.title}\nAssignee: ${task.assignee}\nDue: ${task.due}\nPriority: ${task.priority}`;

  if (settings.autoTasks.notifyAssigneeViaWhatsApp) {
    await sendWhatsApp({
      recipient: task.assignee,
      type: 'Task Assignment',
      message,
      sourceRef: task.id,
    });
  }

  if (settings.autoTasks.notifyAssigneeViaEmail) {
    await sendEmail({
      to: settings.email.ccInternal,
      type: 'Task Assignment',
      subject: `[ERP Task] ${task.title}`,
      body: message,
      sourceRef: task.id,
    });
  }
}

export function notifyTasksUpdate(): void {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('erp-tasks-update'));
  }
}
