import { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { 
  Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter 
} from '@/components/ui/dialog';
import { CalendarClock, CheckSquare, Plus, RefreshCw, Cpu, ExternalLink } from 'lucide-react';
import {
  getAllActiveTasks,
  getAllCompletedTasks,
  createManualTask,
  markTaskDone,
  type Task,
} from '@/lib/taskService';

export default function Tasks() {
  const [activeTasks, setActiveTasks] = useState<Task[]>([]);
  const [completedTasks, setCompletedTasks] = useState<Task[]>([]);
  const [isOpen, setIsOpen] = useState(false);
  const [title, setTitle] = useState('');
  const [assignee, setAssignee] = useState('');
  const [due, setDue] = useState('Today');
  const [priority, setPriority] = useState<'High' | 'Medium' | 'Low'>('Medium');

  const refresh = useCallback(() => {
    setActiveTasks(getAllActiveTasks());
    setCompletedTasks(getAllCompletedTasks());
  }, []);

  useEffect(() => {
    refresh();
    const handler = () => refresh();
    window.addEventListener('erp-tasks-update', handler);
    window.addEventListener('erp-event', handler);
    return () => {
      window.removeEventListener('erp-tasks-update', handler);
      window.removeEventListener('erp-event', handler);
    };
  }, [refresh]);

  const handleCreateTask = (e: React.FormEvent) => {
    e.preventDefault();
    createManualTask({ title, assignee, due, priority });
    setIsOpen(false);
    setTitle('');
    setAssignee('');
    refresh();
  };

  const handleMarkDone = (task: Task) => {
    markTaskDone(task.id);
    refresh();
  };

  const renderTaskCard = (task: Task, column: 'soon' | 'upcoming' | 'done') => {
    const borderColor = column === 'soon' ? 'border-l-rose-500' : column === 'upcoming' ? 'border-l-teal-500' : 'border-l-emerald-500';

    return (
      <Card key={task.id} className={`${borderColor} border-l-4 hover:shadow-md transition-shadow relative overflow-hidden ${column === 'done' ? 'bg-muted/30 opacity-75' : ''}`}>
        {task.isAutoGenerated && (
          <div className={`absolute right-0 top-0 text-[8px] font-bold px-1.5 py-0.5 rounded-bl flex items-center gap-1 uppercase tracking-wider ${
            column === 'done' ? 'bg-zinc-100 text-zinc-400' : 'bg-teal-50 dark:bg-teal-950 text-teal-600 dark:text-teal-400'
          }`}>
            <Cpu className="w-2.5 h-2.5" /> {column === 'done' ? 'Auto' : 'Auto from Details'}
          </div>
        )}
        <CardHeader className="p-4 pb-2">
          <div className="flex justify-between items-start gap-2 mr-10">
            <CardTitle className={`text-sm font-bold leading-tight ${column === 'done' ? 'line-through text-muted-foreground' : ''}`}>
              {task.title}
            </CardTitle>
            {column !== 'done' && (
              <Badge variant={task.priority === 'High' ? 'destructive' : 'secondary'} className="text-[10px] h-4 px-1.5 shrink-0">
                {task.priority}
              </Badge>
            )}
          </div>
          {task.sourcePath && column !== 'done' && (
            <Link to={task.sourcePath} className="text-[10px] text-primary hover:underline flex items-center gap-1 mt-1">
              <ExternalLink className="w-3 h-3" /> View source record
            </Link>
          )}
        </CardHeader>
        <CardContent className="p-4 pt-2">
          <div className="flex justify-between items-end mt-2 text-xs">
            <div className="space-y-1">
              <div className="text-muted-foreground">Assignee: <span className="font-medium text-foreground">{task.assignee}</span></div>
              <div className={column === 'soon' ? 'text-rose-500 font-semibold' : 'text-muted-foreground font-semibold'}>
                Due: {task.due}
              </div>
            </div>
            {column !== 'done' ? (
              <Button size="sm" variant="outline" className="h-7 text-xs border-green-200 text-green-600 hover:bg-green-50" onClick={() => handleMarkDone(task)}>
                <CheckSquare className="mr-1 h-3 w-3" /> Done
              </Button>
            ) : (
              <Badge variant="outline" className="text-emerald-600 border-emerald-600 h-4 bg-emerald-50/50">Done</Badge>
            )}
          </div>
        </CardContent>
      </Card>
    );
  };

  const dueSoon = activeTasks.filter(t => t.due === 'Today' || t.due === 'Tomorrow');
  const upcoming = activeTasks.filter(t => t.due !== 'Today' && t.due !== 'Tomorrow');

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Task Management & Reminders</h2>
          <p className="text-muted-foreground">
            Tasks auto-generate from enquiries, orders, and work orders. WhatsApp & email alerts fire on key events.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="icon" onClick={refresh} title="Refresh tasks from ERP data">
            <RefreshCw className="h-4 w-4" />
          </Button>
          <Button onClick={() => setIsOpen(true)}>
            <Plus className="mr-2 h-4 w-4" /> New Task
          </Button>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <div className="space-y-4">
          <h3 className="font-semibold text-lg flex items-center gap-2">
            <CalendarClock className="h-5 w-5 text-rose-500" /> Due Soon
          </h3>
          {dueSoon.length === 0 ? (
            <div className="text-zinc-400 text-xs text-center py-8 border-2 border-dashed rounded-xl">No tasks due today or tomorrow.</div>
          ) : dueSoon.map(t => renderTaskCard(t, 'soon'))}
        </div>

        <div className="space-y-4">
          <h3 className="font-semibold text-lg flex items-center gap-2">
            <CalendarClock className="h-5 w-5 text-teal-500" /> Upcoming
          </h3>
          {upcoming.length === 0 ? (
            <div className="text-zinc-400 text-xs text-center py-8 border-2 border-dashed rounded-xl">No upcoming tasks scheduled.</div>
          ) : upcoming.map(t => renderTaskCard(t, 'upcoming'))}
        </div>

        <div className="space-y-4">
          <h3 className="font-semibold text-lg flex items-center gap-2">
            <CheckSquare className="h-5 w-5 text-emerald-500" /> Completed
          </h3>
          {completedTasks.length === 0 ? (
            <div className="text-zinc-400 text-xs text-center py-8 border-2 border-dashed rounded-xl">No completed tasks.</div>
          ) : completedTasks.map(t => renderTaskCard(t, 'done'))}
        </div>
      </div>

      <Dialog open={isOpen} onOpenChange={setIsOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <form onSubmit={handleCreateTask}>
            <DialogHeader>
              <DialogTitle>Create New Task</DialogTitle>
              <DialogDescription>Add a manual administrative task or follow-up reminder.</DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="space-y-2">
                <label className="text-sm font-medium">Task Title</label>
                <Input placeholder="e.g. Follow up on quotation QT-26-501" value={title} onChange={e => setTitle(e.target.value)} required />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">Assignee</label>
                <Input placeholder="e.g. Sales Dept" value={assignee} onChange={e => setAssignee(e.target.value)} required />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">Due Date</label>
                <select className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring" value={due} onChange={e => setDue(e.target.value)}>
                  <option value="Today">Today</option>
                  <option value="Tomorrow">Tomorrow</option>
                  <option value="Next Week">Next Week</option>
                </select>
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">Priority</label>
                <select className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring" value={priority} onChange={e => setPriority(e.target.value as 'High' | 'Medium' | 'Low')}>
                  <option value="High">High</option>
                  <option value="Medium">Medium</option>
                  <option value="Low">Low</option>
                </select>
              </div>
            </div>
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => setIsOpen(false)}>Cancel</Button>
              <Button type="submit">Create Task</Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
