import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { 
  Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter 
} from '@/components/ui/dialog';
import { CalendarClock, CheckSquare, Plus, RefreshCw, Cpu, Award } from 'lucide-react';
import { getMockOrders, mockCustomers, mockProducts, mockEnquiries, mockPackingLists } from '@/lib/mockData';
import { mockWorkOrders } from '@/lib/mockData2';
import type { Order } from '@/lib/mockData';
import type { WorkOrder } from '@/lib/mockData2';

interface Task {
  id: string;
  title: string;
  assignee: string;
  due: string;
  status: string;
  priority: string;
  isAutoGenerated?: boolean;
}

export default function Tasks() {
  // Manual (custom) tasks state
  const [manualTasks, setManualTasks] = useState<Task[]>(() => {
    const saved = localStorage.getItem('manualTasks');
    if (saved) return JSON.parse(saved);
    return [
      { id: 'TSK-103', title: 'Schedule AMC Visit for Reliance', assignee: 'Service Coordinator', due: '05-Jul-2026', status: 'Pending', priority: 'Low' }
    ];
  });

  // Completed task IDs (both manual and auto-generated)
  const [completedTaskIds, setCompletedTaskIds] = useState<string[]>(() => {
    const saved = localStorage.getItem('completedTaskIds');
    if (saved) return JSON.parse(saved);
    return ['TSK-100'];
  });

  // Static completed tasks for legacy viewing
  const legacyCompleted: Task[] = [
    { id: 'TSK-100', title: 'Call back vendor regarding MS Plate quote.', assignee: 'Purchase Desk', due: 'Yesterday', status: 'Completed', priority: 'Medium' }
  ];

  // Form states
  const [isOpen, setIsOpen] = useState(false);
  const [title, setTitle] = useState('');
  const [assignee, setAssignee] = useState('');
  const [due, setDue] = useState('Today');
  const [priority, setPriority] = useState('Medium');

  // Trigger state update
  const [tick, setTick] = useState(0);

  // Sync state to local storage
  useEffect(() => {
    localStorage.setItem('manualTasks', JSON.stringify(manualTasks));
    localStorage.setItem('completedTaskIds', JSON.stringify(completedTaskIds));
  }, [manualTasks, completedTaskIds]);

  // Compute Auto-Generated Tasks dynamically based on database states
  const generateAutoTasks = (): Task[] => {
    const autoTasks: Task[] = [];
    const orders = getMockOrders();

    // 1. Follow-up on open enquiries
    mockEnquiries.forEach(enq => {
      if (enq.status === 'Open') {
        const cust = mockCustomers.find(c => c.id === enq.customerId);
        autoTasks.push({
          id: `AUTO-ENQ-${enq.id}`,
          title: `Follow up on open Enquiry ${enq.id} for ${cust?.name || 'Customer'} (Est: ₹${enq.expectedValue.toLocaleString('en-IN')})`,
          assignee: 'Sales Dept',
          due: 'Tomorrow',
          status: 'Pending',
          priority: 'High',
          isAutoGenerated: true
        });
      }
    });

    // 2. Packing list requirements for Ready for Dispatch orders
    orders.forEach(order => {
      const cust = mockCustomers.find(c => c.id === order.customerId);
      if (order.status === 'Ready for Dispatch') {
        const pl = mockPackingLists.find(p => p.orderId === order.id);
        if (!pl) {
          autoTasks.push({
            id: `AUTO-PACK-${order.id}`,
            title: `Configure & finalize Packing List for Order ${order.id} (${cust?.name || 'Customer'})`,
            assignee: 'Logistics Desk',
            due: 'Today',
            status: 'Pending',
            priority: 'High',
            isAutoGenerated: true
          });
        } else if (pl.status === 'Finalized') {
          autoTasks.push({
            id: `AUTO-SHIP-${order.id}`,
            title: `Generate E-Way Bill & Dispatch Carrier for ${order.id} (${cust?.name || 'Customer'})`,
            assignee: 'Transport Desk',
            due: 'Today',
            status: 'Pending',
            priority: 'Medium',
            isAutoGenerated: true
          });
        }
      }
    });

    // 3. Work Orders currently in assembly/testing stages
    // Try to load active work orders from localStorage if any, otherwise fall back to mock
    let activeWos: WorkOrder[] = mockWorkOrders;
    if (typeof window !== 'undefined') {
      const savedWos = localStorage.getItem('mockWorkOrders');
      if (savedWos) activeWos = JSON.parse(savedWos);
    }

    activeWos.forEach(wo => {
      if (wo.status === 'Assembly' || wo.status === 'Testing') {
        const prod = mockProducts.find(p => p.id === wo.productId);
        autoTasks.push({
          id: `AUTO-WO-${wo.id}`,
          title: `Supervise ${wo.status} stage for Job Card ${wo.id} (${prod?.name || 'Product'})`,
          assignee: 'Production Floor',
          due: 'Next Week',
          status: 'Pending',
          priority: 'Medium',
          isAutoGenerated: true
        });
      }
    });

    return autoTasks;
  };

  // Compile active auto-generated tasks (excluding completed ones)
  const activeAutoTasks = generateAutoTasks().filter(t => !completedTaskIds.includes(t.id));

  // Combine manual tasks and active auto tasks
  const allActiveTasks = [
    ...manualTasks.filter(t => !completedTaskIds.includes(t.id)),
    ...activeAutoTasks
  ];

  // Compile all completed tasks (legacy + newly completed)
  const allCompletedTasks = [
    ...legacyCompleted,
    ...manualTasks.filter(t => completedTaskIds.includes(t.id)),
    ...generateAutoTasks().filter(t => completedTaskIds.includes(t.id)).map(t => ({ ...t, status: 'Completed' }))
  ];

  const handleCreateTask = (e: React.FormEvent) => {
    e.preventDefault();
    const newTask: Task = {
      id: `TSK-${104 + manualTasks.length + completedTaskIds.length}`,
      title,
      assignee,
      due,
      status: 'Pending',
      priority
    };
    setManualTasks([...manualTasks, newTask]);
    setIsOpen(false);
    setTitle('');
    setAssignee('');
  };

  const handleMarkDone = (task: Task) => {
    setCompletedTaskIds([...completedTaskIds, task.id]);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight">Task Management & Reminders</h2>
          <p className="text-muted-foreground">Office tasks, follow-ups, and dynamically generated system reminders.</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="icon" onClick={() => setTick(prev => prev + 1)} title="Refresh Dynamic Reminders">
            <RefreshCw className="h-4 w-4" />
          </Button>
          <Button onClick={() => setIsOpen(true)}>
            <Plus className="mr-2 h-4 w-4" /> New Task
          </Button>
        </div>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        {/* Kanban style columns */}
        
        {/* Column 1: Due Soon */}
        <div className="space-y-4">
          <h3 className="font-semibold text-lg flex items-center gap-2">
            <CalendarClock className="h-5 w-5 text-rose-500" /> Due Soon
          </h3>
          {allActiveTasks.filter(t => t.due === 'Today' || t.due === 'Tomorrow').length === 0 ? (
            <div className="text-slate-400 text-xs text-center py-8 border-2 border-dashed rounded-xl">
              No tasks due today or tomorrow.
            </div>
          ) : (
            allActiveTasks.filter(t => t.due === 'Today' || t.due === 'Tomorrow').map(task => (
              <Card key={task.id} className="border-l-4 border-l-rose-500 hover:shadow-md transition-shadow relative overflow-hidden">
                {task.isAutoGenerated && (
                  <div className="absolute right-0 top-0 bg-blue-50 dark:bg-blue-950 text-blue-600 dark:text-blue-400 text-[8px] font-bold px-1.5 py-0.5 rounded-bl flex items-center gap-1 uppercase tracking-wider">
                    <Cpu className="w-2.5 h-2.5" /> Auto Alert
                  </div>
                )}
                <CardHeader className="p-4 pb-2">
                  <div className="flex justify-between items-start gap-2 mr-10">
                    <CardTitle className="text-sm font-bold leading-tight">{task.title}</CardTitle>
                    <Badge variant={task.priority === 'High' ? 'destructive' : 'secondary'} className="text-[10px] h-4 px-1.5 shrink-0">
                      {task.priority}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent className="p-4 pt-2">
                  <div className="flex justify-between items-end mt-2 text-xs">
                    <div className="space-y-1">
                      <div className="text-muted-foreground">Assignee: <span className="font-medium text-foreground">{task.assignee}</span></div>
                      <div className="text-rose-500 font-semibold">Due: {task.due}</div>
                    </div>
                    <Button size="sm" variant="outline" className="h-7 text-xs border-green-200 text-green-600 hover:bg-green-50" onClick={() => handleMarkDone(task)}>
                      <CheckSquare className="mr-1 h-3 w-3" /> Done
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </div>

        {/* Column 2: Upcoming */}
        <div className="space-y-4">
          <h3 className="font-semibold text-lg flex items-center gap-2">
            <CalendarClock className="h-5 w-5 text-blue-500" /> Upcoming
          </h3>
          {allActiveTasks.filter(t => t.due !== 'Today' && t.due !== 'Tomorrow').length === 0 ? (
            <div className="text-slate-400 text-xs text-center py-8 border-2 border-dashed rounded-xl">
              No upcoming tasks scheduled.
            </div>
          ) : (
            allActiveTasks.filter(t => t.due !== 'Today' && t.due !== 'Tomorrow').map(task => (
              <Card key={task.id} className="border-l-4 border-l-blue-500 hover:shadow-md transition-shadow relative overflow-hidden">
                {task.isAutoGenerated && (
                  <div className="absolute right-0 top-0 bg-blue-50 dark:bg-blue-950 text-blue-600 dark:text-blue-400 text-[8px] font-bold px-1.5 py-0.5 rounded-bl flex items-center gap-1 uppercase tracking-wider">
                    <Cpu className="w-2.5 h-2.5" /> Auto Alert
                  </div>
                )}
                <CardHeader className="p-4 pb-2">
                  <div className="flex justify-between items-start gap-2 mr-10">
                    <CardTitle className="text-sm font-bold leading-tight">{task.title}</CardTitle>
                    <Badge variant="secondary" className="text-[10px] h-4 px-1.5 shrink-0">
                      {task.priority}
                    </Badge>
                  </div>
                </CardHeader>
                <CardContent className="p-4 pt-2">
                  <div className="flex justify-between items-end mt-2 text-xs">
                    <div className="space-y-1">
                      <div className="text-muted-foreground">Assignee: <span className="font-medium text-foreground">{task.assignee}</span></div>
                      <div className="text-muted-foreground font-semibold">Due: {task.due}</div>
                    </div>
                    <Button size="sm" variant="outline" className="h-7 text-xs border-green-200 text-green-600 hover:bg-green-50" onClick={() => handleMarkDone(task)}>
                      <CheckSquare className="mr-1 h-3 w-3" /> Done
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </div>

        {/* Column 3: Completed */}
        <div className="space-y-4">
          <h3 className="font-semibold text-lg flex items-center gap-2">
            <CheckSquare className="h-5 w-5 text-emerald-500" /> Completed
          </h3>
          {allCompletedTasks.length === 0 ? (
            <div className="text-slate-400 text-xs text-center py-8 border-2 border-dashed rounded-xl">
              No completed tasks.
            </div>
          ) : (
            allCompletedTasks.map((task, idx) => (
              <Card key={`${task.id}-${idx}`} className="border-l-4 border-l-emerald-500 bg-muted/30 opacity-75 relative overflow-hidden">
                {task.isAutoGenerated && (
                  <div className="absolute right-0 top-0 bg-slate-100 text-slate-400 text-[8px] font-bold px-1.5 py-0.5 rounded-bl flex items-center gap-1 uppercase tracking-wider">
                    Auto
                  </div>
                )}
                <CardHeader className="p-4 pb-1">
                  <CardTitle className="text-sm font-bold leading-tight line-through text-muted-foreground mr-10">{task.title}</CardTitle>
                </CardHeader>
                <CardContent className="p-4 pt-1">
                  <div className="flex justify-between items-center text-[10px] text-muted-foreground">
                    <span>Completed</span>
                    <Badge variant="outline" className="text-emerald-600 border-emerald-600 h-4 bg-emerald-50/50">Done</Badge>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </div>
      </div>

      {/* Manual Task Dialog */}
      <Dialog open={isOpen} onOpenChange={setIsOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <form onSubmit={handleCreateTask}>
            <DialogHeader>
              <DialogTitle>Create New Task</DialogTitle>
              <DialogDescription>
                Add a new administrative task or follow-up reminder.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="space-y-2">
                <label className="text-sm font-medium">Task Title</label>
                <Input 
                  placeholder="e.g. Follow up on quotation QT-26-501" 
                  value={title} 
                  onChange={e => setTitle(e.target.value)} 
                  required 
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">Assignee</label>
                <Input 
                  placeholder="e.g. Sales Dept, Suresh Fitter" 
                  value={assignee} 
                  onChange={e => setAssignee(e.target.value)} 
                  required 
                />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">Due Date</label>
                <select 
                  className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
                  value={due} 
                  onChange={e => setDue(e.target.value)}
                >
                  <option value="Today">Today</option>
                  <option value="Tomorrow">Tomorrow</option>
                  <option value="Next Week">Next Week</option>
                  <option value="15-Jul-2026">15-Jul-2026</option>
                </select>
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">Priority</label>
                <select 
                  className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
                  value={priority} 
                  onChange={e => setPriority(e.target.value)}
                >
                  <option value="High">High</option>
                  <option value="Medium">Medium</option>
                  <option value="Low">Low</option>
                </select>
              </div>
            </div>
            <DialogFooter>
              <Button type="button" variant="outline" onClick={() => setIsOpen(false)}>Cancel</Button>
              <Button type="submit">Create Task</Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}
