import { useParams, Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Printer, ArrowLeft, Send } from 'lucide-react';
import { mockOrders, mockCustomers, mockQuotations, mockProducts } from '@/lib/mockData';

export default function InvoiceDetail() {
  const { id } = useParams();
  const order = mockOrders.find(o => o.id === id);
  const quotation = mockQuotations.find(q => q.id === order?.quotationId);
  const customer = mockCustomers.find(c => c.id === order?.customerId);

  if (!order || !customer) {
    return <div>Order/Invoice not found</div>;
  }

  const handlePrint = () => window.print();

  const totalBasic = order.totalAmount;
  const totalGST = totalBasic * 0.18;
  const grandTotal = totalBasic + totalGST;

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4 print:hidden">
        <Link to="/accounting">
          <Button variant="outline" size="icon">
            <ArrowLeft className="h-4 w-4" />
          </Button>
        </Link>
        <div className="flex-1">
          <h2 className="text-3xl font-bold tracking-tight">Tax Invoice</h2>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handlePrint}>
            <Printer className="mr-2 h-4 w-4" /> Print
          </Button>
          <Button>
            <Send className="mr-2 h-4 w-4" /> Send to IRN Portal
          </Button>
        </div>
      </div>

      {/* Printable Area */}
      <div className="bg-white text-black p-8 shadow-sm border rounded-lg max-w-4xl mx-auto print:shadow-none print:border-none print:p-0 font-sans">
        
        {/* Header & QR */}
        <div className="flex justify-between items-start mb-4">
          <div>
            <h1 className="text-3xl font-bold text-primary mb-1">SUMESH PETROLEUM PVT. LTD.</h1>
            <p className="text-sm text-gray-600">Makarpura GIDC, Vadodara, Gujarat - 390010</p>
            <p className="text-sm text-gray-600">Email: accounts@sumeshpetroleum.com</p>
            <p className="text-sm font-semibold mt-1">GSTIN: 24AAACSXXXXA1Z5</p>
          </div>
          <div className="text-right flex flex-col items-end">
            <h2 className="text-2xl font-bold tracking-widest uppercase mb-2">TAX INVOICE</h2>
            {/* Fake IRN QR Code Placeholder */}
            <div className="w-24 h-24 bg-gray-200 border border-gray-400 p-1 flex items-center justify-center">
              <span className="text-[10px] text-gray-500 text-center">B2B IRN<br/>QR CODE</span>
            </div>
          </div>
        </div>

        <div className="text-xs text-gray-500 mb-4 break-all">
          <strong>IRN:</strong> 35d3d4b655f46a9e88bb... (Auto-generated by NIC portal)
        </div>

        {/* Invoice Meta Grid */}
        <div className="flex border border-gray-400 mb-6 text-sm">
          <div className="w-1/2 border-r border-gray-400 p-4 flex flex-col justify-between">
            <div>
              <h3 className="font-semibold text-gray-700 mb-2 border-b border-gray-200 pb-1">Billed To:</h3>
              <p className="font-bold text-gray-900">{customer.name}</p>
              <p className="text-gray-700 whitespace-pre-line">{customer.address}</p>
              <p className="text-gray-700">{customer.city}, {customer.state}</p>
              <p className="mt-2"><strong>GSTIN/UIN:</strong> {customer.gstin}</p>
              <p><strong>State Name:</strong> {customer.state}, Code: 24</p>
            </div>
          </div>
          <div className="w-1/2 p-0 flex flex-col">
            <div className="flex border-b border-gray-400">
              <div className="w-1/2 border-r border-gray-400 p-2">
                <span className="text-xs text-gray-500 block">Invoice No.</span>
                <span className="font-semibold">INV-26-1240</span>
              </div>
              <div className="w-1/2 p-2">
                <span className="text-xs text-gray-500 block">Dated</span>
                <span className="font-semibold">30-Jun-2026</span>
              </div>
            </div>
            <div className="flex border-b border-gray-400">
              <div className="w-1/2 border-r border-gray-400 p-2">
                <span className="text-xs text-gray-500 block">Delivery Note</span>
                <span className="font-semibold">DC-26-880</span>
              </div>
              <div className="w-1/2 p-2">
                <span className="text-xs text-gray-500 block">Mode/Terms of Payment</span>
                <span className="font-semibold">100% Advance</span>
              </div>
            </div>
            <div className="flex border-b border-gray-400">
              <div className="w-1/2 border-r border-gray-400 p-2">
                <span className="text-xs text-gray-500 block">Buyer's Order No.</span>
                <span className="font-semibold">{order.id}</span>
              </div>
              <div className="w-1/2 p-2">
                <span className="text-xs text-gray-500 block">Dated</span>
                <span className="font-semibold">{order.date}</span>
              </div>
            </div>
            <div className="flex flex-1">
              <div className="w-full p-2">
                <span className="text-xs text-gray-500 block">Terms of Delivery</span>
                <span className="font-semibold text-xs">Ex-Works Vadodara. Freight To Pay.</span>
              </div>
            </div>
          </div>
        </div>

        {/* Line Items */}
        <table className="w-full border-collapse border border-gray-400 text-sm mb-6">
          <thead className="bg-gray-100">
            <tr>
              <th className="border border-gray-400 p-2 text-left w-10">Sr</th>
              <th className="border border-gray-400 p-2 text-left">Description of Goods</th>
              <th className="border border-gray-400 p-2 text-center w-20">HSN/SAC</th>
              <th className="border border-gray-400 p-2 text-center w-16">Qty</th>
              <th className="border border-gray-400 p-2 text-right w-24">Rate</th>
              <th className="border border-gray-400 p-2 text-center w-16">per</th>
              <th className="border border-gray-400 p-2 text-right w-28">Amount</th>
            </tr>
          </thead>
          <tbody className="h-48 align-top">
            {quotation?.items.map((item, index) => {
              const product = mockProducts.find(p => p.id === item.productId);
              return (
                <tr key={index}>
                  <td className="border-x border-gray-400 p-2 text-center">{index + 1}</td>
                  <td className="border-x border-gray-400 p-2">
                    <p className="font-semibold">{product?.name}</p>
                    <p className="text-xs text-gray-600 mt-1">Machine S.No: SP/26/1012</p>
                  </td>
                  <td className="border-x border-gray-400 p-2 text-center">84212900</td>
                  <td className="border-x border-gray-400 p-2 text-center font-semibold">{item.quantity}</td>
                  <td className="border-x border-gray-400 p-2 text-right">{item.unitPrice.toLocaleString('en-IN')}</td>
                  <td className="border-x border-gray-400 p-2 text-center">Nos</td>
                  <td className="border-x border-gray-400 p-2 text-right font-medium">
                    {(item.quantity * item.unitPrice).toLocaleString('en-IN')}
                  </td>
                </tr>
              );
            })}
            
            {/* Empty space filler for format */}
            <tr>
              <td className="border-x border-gray-400 p-2"></td>
              <td className="border-x border-gray-400 p-2"></td>
              <td className="border-x border-gray-400 p-2"></td>
              <td className="border-x border-gray-400 p-2"></td>
              <td className="border-x border-gray-400 p-2"></td>
              <td className="border-x border-gray-400 p-2"></td>
              <td className="border-x border-gray-400 p-2"></td>
            </tr>
          </tbody>
          <tfoot>
            <tr className="border border-gray-400">
              <td colSpan={6} className="p-2 text-right">Total Basic Value</td>
              <td className="p-2 text-right font-semibold border-l border-gray-400">₹{totalBasic.toLocaleString('en-IN')}</td>
            </tr>
            <tr className="border border-gray-400">
              <td colSpan={6} className="p-2 text-right">Output CGST @ 9%</td>
              <td className="p-2 text-right border-l border-gray-400">₹{(totalGST/2).toLocaleString('en-IN')}</td>
            </tr>
            <tr className="border border-gray-400">
              <td colSpan={6} className="p-2 text-right">Output SGST @ 9%</td>
              <td className="p-2 text-right border-l border-gray-400">₹{(totalGST/2).toLocaleString('en-IN')}</td>
            </tr>
            <tr className="border border-gray-400 bg-gray-50">
              <td colSpan={6} className="p-2 text-right font-bold">Grand Total</td>
              <td className="p-2 text-right font-bold border-l border-gray-400 text-lg">₹{grandTotal.toLocaleString('en-IN')}</td>
            </tr>
          </tfoot>
        </table>

        {/* Footer info */}
        <div className="flex text-sm">
          <div className="w-1/2 pr-4">
            <h4 className="font-semibold underline mb-2">Declaration</h4>
            <p className="text-gray-700 text-xs text-justify">
              We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct. All disputes are subject to Vadodara jurisdiction only.
            </p>
          </div>
          <div className="w-1/2 border border-gray-400 p-0 flex flex-col">
            <div className="p-2 flex-1 relative min-h-[100px]">
              <span className="absolute top-2 left-2 text-xs text-gray-500">For Sumesh Petroleum Pvt. Ltd.</span>
              <span className="absolute bottom-2 left-2 text-xs font-semibold">Authorized Signatory</span>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
